### ISSUE TITLE
下载被中断

### ISSUE THREAD

**Issue by Proby143** [lightsing/crates-mirror-ngx#14]
错误提示如下：
Caused by:
  failed to download from `https://static.crates-io.cn/autocfg/1.0.1`

Caused by:
  failed to get 200 response from `https://static.crates-io.cn/autocfg/1.0.1`, got 403

Caused by:
  failed to download from `https://static.crates-io.cn/autocfg/1.0.1`

Caused by:
  failed to get 200 response from `https://static.crates-io.cn/autocfg/1.0.1`, got 403

注：浏览器能下载到包

**Comment by lightsing** [comment]
issue confirmed

**Comment by lightsing** [comment]
问题确认：cargo 请求文件时并非都携带了 User-Agent，导致被安全规则拦截
已修复
